### ISSUE TITLE
Verification of @NamedInterface's with the same name

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-modulith#168]
Allow multiple `@NamedInterface` with the same name to be allowed as module dependencies.

Let me illustrate:
```
Example
└─ src/main/java
   ├─ infra
   |  ├— package-info.java
   |  └─ ⊕ SomeInterfaceImpl.java
   ├─ application
   |  ├─ ⊕ Application.java
   |  ├─ ⊕ SomeInterface.java
   |  └— package-info.java
   ├─ domain
   |  ├─ ⊕ ...
   |  ├— order
   |  |  ├— model
   |  |  |  └─ ⊖ SomeModel.java
   |  |  └— vo
   |  |     └─ ⊖ SomeVO.java
   |  └— cart
   |     ├— model
   |     |  └─ ⊖ SomeModel.java
   |     └— vo
   |        └─ ⊖ SomeVO.java
```

What I do is to assign the same names to the NamedInterface's that constains the same type of classes, e.g.:
```
Example
└─ src/main/java
   ├─ infra
   |  └─ ...
   ├─ application
   |  └— ...
   ├─ domain
   |  ├─ ⊕ ...
   |  ├— order
   |  |  ├— model (allowed via @NamedInterface names: model, order-model)
   |  |  |  ├─ ⊕ SomeModel.java
   |  |  |  └─ package-info.java
   |  |  └— vo (allowed via @NamedInterface names: vo, order-vo)
   |  |     ├─ ⊕ SomeVO.java
   |  |     └─ package-info.java
   |  └— cart
   |     ├— model (allowed via @NamedInterface names: model, cart-model)
   |     |  ├─ ⊕ SomeModel.java
   |     |  └─ package-info.java
   |     └— vo (allowed via @NamedInterface names: vo, cart-vo)
   |        ├─ ⊕ SomeVO.java
   |        └─ package-info.java
```

What I liked to accomplish during the verification test (`ApplicationModules.of(...).verify()`) when for example I declare a allowed dependency from the `application` module to all `domain::vo` named interfaces is that the test don't fail with violation errors.

**Comment by aalbiach-dkt** [comment]
The above example is a vague representation to show you the desired behaviour, I do not consider this to be the point of the matter.

The main modules are infra, application and domain. The `Application.java` defines the `@Modulith` annotation.
In every module I defined their name and the allowed dependencies. So, the dependencies between modules would be:

> **infra** depends on  **application** and **domain**
> **application** depends on **domain**
> **domain** no dependencies

Understanding this, if I have multiple packages in domain or application we need to create multiple `@NamedInterface` per package because every subpackage is internal by default.
The `@NamedInterface` has the `name` property which is of type `String[]`, so it is understood that I can add multiple names to the same `@NamedInterface`. In the Javadoc you can read the following:

> The name(s) of the named interface. Declaring multiple values here is useful in case named interfaces are defined based on types and a particular type is supposed to be part of multiple named interfaces.

So, going back to the beginning, if the `domain.order.model` and `domain.cart.model` package share the same name `model` in their `@NamedInterface`, I could create a dependency from the application module to the domain module as follows:

```java
// package-info.java

@org.springframework.modulith.ApplicationModule(
    displayName = "application",
    allowedDependencies = {"domain", "domain::model"})
package application;
``` 

But actually, the behaviour is that the verification test fails with violation errors because the `NamedInterfaces::getByName( name)` returns only the first match even if there are multiple.

**Comment by odrotbohm** [comment]
> The main modules are infra, application and domain.

I guess this is where the problem starts. Those are *not* modules, they are technical abstractions. Modules are units of cohesion. In other words: units, in which the important relationships are established *within* a unit, not *across* them. What you do here is prioritizing technical separation over functional. You can, of course, do that, but that's swimming against the design philosophy of Spring Modulith in the first place. You can really feel this by realizing that the dependency declarations become unnecessarily awkward. I talk about this in [this presentation](https://www.youtube.com/watch?v=SjSjBZ7mo1g) on Spring Modulith quite extensively.

I can only recommend on the *functional separation* (`cart`, `order`) and not over-divide underneath that. There's really no point in putting all value objects in a dedicated VO package if all those types need to be public anyway. That's a bit like putting all `String` fields into the same class.
