### ISSUE TITLE
`MultipartFile` instance empty when consumed via an `@ApplicationModuleListener`

### ISSUE THREAD

**Issue by eynoc-coder** [spring-projects/spring-modulith#249]
Hi, I have a use case where I have to publish an event containing a MultipartFile.

In the publisher method the file is not empty but in the Listener it's becoming empty. Don't really know how to handle it.

the publisher
```java
  
  @Override
  @Transactional
  public void addImage(String slug, Long institutionId, MultipartFile image) {
   // image is not empty here.
    events.publishEvent(new ProductFile(slug, image, "product", institutionId));
  }

```

the listener

```java
  @Override
  @ApplicationModuleListener
  public void on(ProductFile event) {
    // But it is empty here.
    File file = fileAssembler.toFile(event.file(), event.folder());
    String path = fileService.save(file);
    events.publishEvent(new ProductFileResponse(path, event.slug(), event.institutionId()));
  }
```

And the properties size of servlet and request  max size is well set.

**Comment by odrotbohm** [comment]
I guess the problem here is that a `MultipartFile` is directly backed by the input stream of the incoming request, which in turn is tied to the thread receiving it. Any chance you copy the content into a separate data structure first?

Just to make sure: it's not obvious from the code you showed what exactly happens to the `MultipartImage` within `ProductFile`. You just state “it is empty” without clarifying what “it” refers to.

Finally, the code in the listener looks a bit suspicious. Application module listeners are intended to react to *completed* units of work in a foreign model. They are not intended to re-implement a request/response via events. In other words, we recommend the original business transaction to result in a valid state and the events solely transferring pointers to that state.
