### ISSUE TITLE
Release 1.1 M1

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-modulith#303]

**Comment by patrickuhlmann** [comment]
In the [documentation](https://docs.spring.io/spring-modulith/docs/1.1.0-SNAPSHOT/reference/html/#events.publication-registry.managing-publications) there is mentioned that there are Beans for the interfaces CompletedEventPublications  and IncompleteEventPublications but when I used the Snapshot-1.1 Version in Spring Boot no beans were found for these interfaces?

**Comment by patrickuhlmann** [comment]
Ok thanks. Then probably this happened because we mixed the 1.0 core and the 1.1 events dependencies.

**Comment by patrickuhlmann** [comment]
There is still something off. I checked out https://github.com/spring-projects/spring-modulith/tree/main/spring-modulith-examples/spring-modulith-example-full and then added `private final CompletedEventPublications pub;` in the InventoryManagement. 

Starting fails
`Parameter 1 of constructor in example.inventory.InventoryManagement required a bean of type 'org.springframework.modulith.events.CompletedEventPublications' that could not be found.`

Upon further investigation I saw in the debug log for autoconfiguration
`   EventPublicationAutoConfiguration#eventPublicationRegistry:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.modulith.events.core.EventPublicationRepository; SearchStrategy: all) did not find any beans of type org.springframework.modulith.events.core.EventPublicationRepository (OnBeanCondition)`

In the test you added it is working because in your basic setup you provide a mock for EventPublicationRepository. However in regular usage there seems to be no bean for EventPublicationRepository available.

**Comment by patrickuhlmann** [comment]
The error disappears when I add
`		<dependency>
			<groupId>org.springframework.modulith</groupId>
			<artifactId>spring-modulith-events-jpa</artifactId>
			<version>1.1.1</version>
		</dependency>`

but a bean is still not available for CompletedEventPublications as the JpaEventPublicationRepository does not implement it. Still a bit brittle...

**Comment by odrotbohm** [comment]
The problem shouldn't be related to the dependency setup but caused by a suboptimal configuration setup that causes non-deterministic lookups depending on at which configuration phase the injection point needs to be satisfied. As a slightly differently configured classpath might influence the order of the instantiation, it could certainly have an effect on whether the injection succeeds or fails.

I've filed #443 to fix the root cause of this so that `CEP` will be consistently available for DI.
