### ISSUE TITLE
Spring Modulith Docs as maven report

### ISSUE THREAD

**Issue by wolframhaussig** [spring-projects/spring-modulith#314]
I am starting to use Spring Modulith in a small project to check it out and I find it very helpful so far. But I have a minor wish for the documentation:
I am using `mvn site` to generate the documentation of my project but this does not contain the module documentation. Would it be possible to create a [maven report plugin](https://maven.apache.org/guides/plugin/guide-java-report-plugin-development.html) to add the module docs to the maven generated documentation?

**Comment by khmarbaise** [comment]
The modulith docs are asciidoc parts (PlantUML, asciidoctor) If you use [asciidoctor-maven-plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin) (see for details https://github.com/asciidoctor/asciidoctor-maven-examples/tree/main/asciidoc-maven-site-example) it can be integrated into the site as well (you can write asciidoc for the site parts instead of apt, markdown etc.). The option to generate the javadoc including umldcolet can be integrated into the site anyway...

**Comment by odrotbohm** [comment]
I currently don't think we want to expand the scope of our functionality into build system-specific extensions. As Karl Heinz pointed out, we're generating PlantUML and Asciidoc files into well-known locations. You should be able to configure your build system to pick those files up from those locations. A common pattern is to include both the PlantUML and Asciidoc files into a central file rendered by the Asciidoctor Maven plugin for downstream consumption.

**Comment by breun** [comment]
I understand your arguments too, but every colleague I've shown this so far thought it was strange that the recommendation is to generate these files by running a test. I understand that it is convenient, because it works regardless of which build tool is used. Your suggestion to call `Documenter` from a separate `main` is interesting, I might give that a try.

**Comment by odrotbohm** [comment]
Note, that there is also precedent in executing tests to generate documentation in response to a succeeded test in Spring REST Docs. While we are admittedly implicitly assuming the `ApplicationModules` instance has been verified, the situation is structurally equivalent.
