### ISSUE TITLE
`CompletedEventPublications.deletePublications(…)` deletes incomplete publications

### ISSUE THREAD

**Issue by AnthonySlabinck** [spring-projects/spring-modulith#491]
The Javadoc says that the ```CompletedEventPublications``` interface allows accessing all completed event publications, but actually underlying it calls the ```EventPublicationRegistry#findIncompletePublications```.

This generates following query:
```
Hibernate: select jep1_0.id,jep1_0.completion_date,jep1_0.event_type,jep1_0.listener_id,jep1_0.publication_date,jep1_0.serialized_event from event_publication jep1_0 where jep1_0.completion_date is null order by jep1_0.publication_date
```
My code:
```java
import java.time.Duration;
import lombok.RequiredArgsConstructor;
import org.springframework.modulith.events.CompletedEventPublications;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class OutboxService {

    private final CompletedEventPublications completedEventPublications;

    @Transactional
    void deleteCompletedPublications() {
        completedEventPublications.deletePublicationsOlderThan(Duration.ofMinutes(30));
    }

}
```

I hope the provided information is enough. 
Kind regards.

**Comment by lukasdo** [comment]
@AnthonySlabinck as you already mentioned the `CompletedEventPublications` implementation called the wrong method of the `EventPublicationRepository`. I crafted a PR to address this issue, so that the JavaDoc and official modulith documentation aligns with the code. 

@odrotbohm  If desired I could add a test to ensure the correct behaviour of the `DefaultEventPublicationRegistry` in the future.

**Comment by odrotbohm** [comment]
I've added comments on GH-491.
