### ISSUE TITLE
Injection of internal beans defined into module1 is allowed in module2 internals

### ISSUE THREAD

**Issue by aribeth007** [spring-projects/spring-modulith#807]
Hi all,

Writing this issue since I'm not sure if this is desired behavior, please feel flee to close this directly if so.

I did the following test (1.3.0-M2):
- Created two beans in module1/internal/Module1Config.java [(Here)](https://github.com/aribeth007/modulith-example/blob/main/src/main/java/com/example/modulith/module1/internal/Module1Config.java)
- Injected the beans in module2/internal/Module2Service.java [(Here)](https://github.com/aribeth007/modulith-example/blob/main/src/main/java/com/example/modulith/module2/internal/Module2Service.java)
- Ran the verify modular structure test which **Passed**

Using Spring Modulith 1.3.0-M2 , also usign lombok as you can see in the above examples.

At the moment , i was expecting this to fail. Let me know what you think about the scenario.

**Comment by odrotbohm** [comment]
The code in the examples does not match your description:

* `module2.internal.Module2Service` does *not* depend on `Module1Config`. A mere import statement does not constitute a dependency. If I actually add the dependency by declaring a field or parameter, it's creating a violation.
* without any changes, an erroneous violation between `Module32Service` and `Module31Interface` is reported, which you already reported in GH-787 and is fixed in 1.3 snapshots.

**Comment by aribeth007** [comment]
https://github.com/aribeth007/modulith-example/blob/main/src/main/java/com/example/modulith/module2/internal/Module2Service.java#L18-L20

I was actually refering not to the import itself but to the beans that are injected into Module2Service at lines18 and 20.. which are defined into module1config

**Comment by odrotbohm** [comment]
Those do not establish a dependency to `module1` though, as the instances could come from anywhere. What we monitor is type dependencies, not the origins of beans.

**Comment by aribeth007** [comment]
ok, understood, thanks so much for taking the time to look into this

**Comment by odrotbohm** [comment]
Sure thing. Thanks for giving the preview versions a try. Really appreciated!
