### ISSUE TITLE
Compile-time support for 'org.springframework.modulith.core'

### ISSUE THREAD

**Issue by hyeonseokhan** [spring-projects/spring-modulith#943]
I want to implement ApplicationModuleDetectionStrategy to change the base package. However, I am encountering a compilation error as shown below and am looking for a solution.

![image](https://github.com/user-attachments/assets/af8fc9fd-4f3c-4c74-8984-98b754059494)

and gradle setting
```text
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.toyproject'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springModulithVersion', "1.2.4")
}


dependencies {
    implementation fileTree(dir: "./libs", includes: ["*.jar"])
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'commons-codec:commons-codec:1.17.1'

    // Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.boot:spring-boot-starter-aop'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Spring Modulith
    implementation 'org.springframework.modulith:spring-modulith-starter-core'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'com.zaxxer:HikariCP:5.0.1'
    implementation 'com.h2database:h2:2.2.220'

    implementation 'org.web3j:core:4.12.1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
```
![image](https://github.com/user-attachments/assets/ab7a7460-2213-4033-847c-9615242992b3)

**Comment by odrotbohm** [comment]
`ApplicationModuleDetectionStrategy` is contained in the `spring-modulith-core` artifact, which is only imported in `runtime` scope by `spring-modulith-starter-core` (as documented [here](https://docs.spring.io/spring-modulith/reference/appendix.html#artifacts)). If you want to customize your module setup, you additionally need to declare `spring-modulith-core` as a compile scope dependency.

I'll make sure we add a corresponding note to the relevant sections of the reference documentation.

**Comment by ciberkleid** [comment]
Docs have been updated to say that:
- If you are customizing `ApplicationModuleDetectionStrategy` for module verification or documentation, you should place the code (and corresponding `application.properties` registration) in your application's test sources as `spring-modulith-starter-core` is included under `test` scope by `spring-modulith-starter-test`
- Otherwise, if your customization is for runtime purposes, you need to explicitly declare `spring-modulith-starter-core` as a compile-time dependency.

**Comment by ciberkleid** [comment]
Docs have been updated to say that:

- If you are customizing ApplicationModuleDetectionStrategy for module verification or documentation, you should place the code (and corresponding application.properties registration) in your application's test sources as spring-modulith-core is included under test scope by spring-modulith-starter-test
- Otherwise, if your customization is for runtime purposes, you need to explicitly declare spring-modulith-core as a compile-time dependency.
